#dockerfile adminer
FROM adminer

#puerto
EXPOSE 8080

#desde la carpeta Adminer hacemos docker run -t adminer -p 8080:8080 my-adminer:latest

#y luego docker run -t adminer -p 8080:8080 my-adminer:latest

#pero esta dando error ya que el mysql y el adminer no se conocen, toca con docker compose

#vamos a parar los dos dockers y vamos a crear el docker-compose.yml